/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProdutoDAO;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author Lucas
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbdProdutos = new javax.swing.JTabbedPane();
        tbdPnlDadosBasicos = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblIdFornecedor = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtIdFornecedor = new javax.swing.JTextField();
        btnIdPesquisar = new javax.swing.JButton();
        lblEstoque = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        fmtPreco = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        tbdPnlConsultaProdutos = new javax.swing.JPanel();
        lblDescricaoPesquisar = new javax.swing.JLabel();
        txtDescricaoPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tbdProdutos.setBackground(new java.awt.Color(255, 255, 255));
        tbdProdutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbdProdutosFocusGained(evt);
            }
        });

        tbdPnlDadosBasicos.setBackground(new java.awt.Color(255, 255, 255));

        lblId.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblId.setText("ID");

        lblDescricao.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblDescricao.setText("Descricao");

        lblPreco.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblPreco.setText("Preço");

        lblIdFornecedor.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblIdFornecedor.setText("Id fornecedor");

        btnIdPesquisar.setText("Pesquisar");
        btnIdPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdPesquisarActionPerformed(evt);
            }
        });

        lblEstoque.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblEstoque.setText("Estoque");

        fmtPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤ #,##0.00"))));

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));

        btnCadastrar.setText("+Novo");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tbdPnlDadosBasicosLayout = new javax.swing.GroupLayout(tbdPnlDadosBasicos);
        tbdPnlDadosBasicos.setLayout(tbdPnlDadosBasicosLayout);
        tbdPnlDadosBasicosLayout.setHorizontalGroup(
            tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                        .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblEstoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIdPesquisar))
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lblPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fmtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(lblIdFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 356, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tbdPnlDadosBasicosLayout.setVerticalGroup(
            tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdPesquisar))
                .addGap(18, 18, 18)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(fmtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstoque)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdFornecedor)
                    .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbdProdutos.addTab("Dados básicos", tbdPnlDadosBasicos);

        tbdPnlConsultaProdutos.setBackground(new java.awt.Color(255, 255, 255));

        lblDescricaoPesquisar.setText("Nome:");

        txtDescricaoPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoPesquisarKeyReleased(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descricao", "Preco", "Estoque", "Id fabricante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos);

        javax.swing.GroupLayout tbdPnlConsultaProdutosLayout = new javax.swing.GroupLayout(tbdPnlConsultaProdutos);
        tbdPnlConsultaProdutos.setLayout(tbdPnlConsultaProdutosLayout);
        tbdPnlConsultaProdutosLayout.setHorizontalGroup(
            tbdPnlConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlConsultaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbdPnlConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(tbdPnlConsultaProdutosLayout.createSequentialGroup()
                        .addComponent(lblDescricaoPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tbdPnlConsultaProdutosLayout.setVerticalGroup(
            tbdPnlConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlConsultaProdutosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tbdPnlConsultaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoPesquisar)
                    .addComponent(txtDescricaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdProdutos.addTab("Consulta de produtos", tbdPnlConsultaProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbdProdutos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbdProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        tbdProdutos.setSelectedIndex(0);
        int linha = tblProdutos.getSelectedRow();

        txtId.setText(tblProdutos.getValueAt(linha, 0).toString());
        txtDescricao.setText(tblProdutos.getValueAt(linha, 1).toString());
        fmtPreco.setText(tblProdutos.getValueAt(linha, 2).toString());
        txtEstoque.setText(tblProdutos.getValueAt(linha, 3).toString());
        txtIdFornecedor.setText(tblProdutos.getValueAt(linha, 4).toString());
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void txtDescricaoPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoPesquisarKeyReleased
        txtDescricaoPesquisar.setText(txtDescricaoPesquisar.getText().trim());
        listar(txtDescricaoPesquisar.getText());
    }//GEN-LAST:event_txtDescricaoPesquisarKeyReleased

    private void tbdProdutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbdProdutosFocusGained
        txtDescricaoPesquisar.setText(txtDescricaoPesquisar.getText().trim());
        listar(txtDescricaoPesquisar.getText());
    }//GEN-LAST:event_tbdProdutosFocusGained

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Produto produto = new Produto();

        produto.setId(Integer.parseInt(txtId.getText()));
        produto.setDescricao(txtDescricao.getText());
        produto.setPreco(Double.parseDouble(fmtPreco.getText()));
        produto.setEstoque(Integer.parseInt(txtEstoque.getText()));
        produto.setIdFornecedor(Integer.parseInt(txtIdFornecedor.getText()));

        ProdutoDAO dao = new ProdutoDAO();

        dao.alterarProduto(produto);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        Produto produto = new Produto();
        produto.setId(Integer.parseInt(txtId.getText()));

        ProdutoDAO produtoDao = new ProdutoDAO();
        if(produtoDao.deletarProduto(produto))
        {
            utilitarios.Utilitarios.LimpaTela(tbdPnlDadosBasicos);
            JOptionPane.showMessageDialog(null, "Produto deletado com sucesso ;)");
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Produto produto = new Produto();

        produto.setDescricao(txtDescricao.getText());
        produto.setPreco(Double.parseDouble(fmtPreco.getText()));
        produto.setEstoque(Integer.parseInt(txtEstoque.getText()));
        produto.setIdFornecedor(Integer.parseInt(txtIdFornecedor.getText()));

        ProdutoDAO dao = new ProdutoDAO();

        dao.cadastrarProduto(produto);
        utilitarios.Utilitarios.LimpaTela(tbdPnlDadosBasicos);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnIdPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdPesquisarActionPerformed
        utilitarios.Utilitarios.LimpaTela(tbdPnlDadosBasicos);
    }//GEN-LAST:event_btnIdPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }
    
    public void listar()
    {
        ProdutoDAO produtoDao = new ProdutoDAO();
        List<Produto> produtos = produtoDao.obterProdutos();
        
        DefaultTableModel tabelaDados = (DefaultTableModel) tblProdutos.getModel();
        tabelaDados.setNumRows(0);
        
        for(Produto produto : produtos)
        {
            tabelaDados.addRow(
                new Object[]{
                    produto.getId(),
                    produto.getDescricao(),
                    produto.getPreco(),
                    produto.getEstoque(),
                    produto.getIdFornecedor(),
                }
            );
        }
    }
    
        public void listar(String descricao)
    {
        ProdutoDAO produtoDao = new ProdutoDAO();
        List<Produto> produtos = produtoDao.obterProdutos(descricao);
        
        DefaultTableModel tabelaDados = (DefaultTableModel) tblProdutos.getModel();
        tabelaDados.setNumRows(0);
        
        for(Produto produto : produtos)
        {
            tabelaDados.addRow(
                new Object[]{
                    produto.getId(),
                    produto.getDescricao(),
                    produto.getPreco(),
                    produto.getEstoque(),
                    produto.getIdFornecedor(),
                }
            );
        }

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnIdPesquisar;
    private javax.swing.JFormattedTextField fmtPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricaoPesquisar;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdFornecedor;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JPanel tbdPnlConsultaProdutos;
    private javax.swing.JPanel tbdPnlDadosBasicos;
    private javax.swing.JTabbedPane tbdProdutos;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricaoPesquisar;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdFornecedor;
    // End of variables declaration//GEN-END:variables
}
