/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FornecedorDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Fornecedor;

/**
 *
 * @author Lucas
 */
public class TelaFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form TelaFornecedores
     */
    public TelaFornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbdFornecedores = new javax.swing.JTabbedPane();
        tbdPnlDadosBasicos = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnIdPesquisar = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        fmtCnpj = new javax.swing.JFormattedTextField();
        fmtTelefone = new javax.swing.JFormattedTextField();
        fmtCelular = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        fmtCep = new javax.swing.JFormattedTextField();
        lblCep = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbINumero = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        cboUf = new javax.swing.JComboBox<>();
        tbdPnlConsultaFornecedores = new javax.swing.JPanel();
        lblDescricaoPesquisar = new javax.swing.JLabel();
        txtNomePesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de fornecedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tbdFornecedores.setBackground(new java.awt.Color(255, 255, 255));

        tbdPnlDadosBasicos.setBackground(new java.awt.Color(255, 255, 255));

        lblId.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblId.setText("ID");

        lblNome.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblNome.setText("Nome");

        lblCnpj.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCnpj.setText("Cnpj");

        btnIdPesquisar.setText("Pesquisar");
        btnIdPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdPesquisarActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblEmail.setText("Email");

        try {
            fmtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            fmtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            fmtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblTelefone.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblTelefone.setText("Telefone");

        lblCelular.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCelular.setText("Celular");

        try {
            fmtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCep.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCep.setText("Cep");

        lbINumero.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lbINumero.setText("Numero");

        lblEndereco.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblEndereco.setText("Endereço");

        lblComplemento.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblComplemento.setText("Complemento");

        lblBairro.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblBairro.setText("Bairro");

        lblCidade.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCidade.setText("Cidade");

        lblUf.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblUf.setText("Estado");

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));

        btnCadastrar.setText("+Novo");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        cboUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DF", "GO", "MT", "MS", "AL", "BH", "CE", "MA", "PB", "PE", "PI", "RN", "SE", "AC", "AP", "AM", "PA", "RO", "RR", "TO", "ES", "MG", "RJ", "SP", "PR", "RS", "SC", " " }));

        javax.swing.GroupLayout tbdPnlDadosBasicosLayout = new javax.swing.GroupLayout(tbdPnlDadosBasicos);
        tbdPnlDadosBasicos.setLayout(tbdPnlDadosBasicosLayout);
        tbdPnlDadosBasicosLayout.setHorizontalGroup(
            tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                        .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblId)
                                .addComponent(lblEmail)
                                .addComponent(lblCep))
                            .addComponent(lblBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbINumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIdPesquisar)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCnpj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fmtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCelular)))
                                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fmtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(fmtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblUf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tbdPnlDadosBasicosLayout.setVerticalGroup(
            tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlDadosBasicosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdPesquisar)
                    .addComponent(lblCnpj)
                    .addComponent(fmtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblTelefone)
                    .addComponent(fmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular)
                    .addComponent(fmtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(fmtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUf)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tbdPnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbINumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbdFornecedores.addTab("Dados básicos", tbdPnlDadosBasicos);

        tbdPnlConsultaFornecedores.setBackground(new java.awt.Color(255, 255, 255));
        tbdPnlConsultaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdPnlConsultaFornecedoresMouseClicked(evt);
            }
        });

        lblDescricaoPesquisar.setText("Nome:");

        txtNomePesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomePesquisarKeyReleased(evt);
            }
        });

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "CNPJ", "Nome", "Email", "Telefone", "Celular", "CEP", "Estado", "Cidade", "Bairro", "Endereco", "Numero", "Complemento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFornecedores);

        javax.swing.GroupLayout tbdPnlConsultaFornecedoresLayout = new javax.swing.GroupLayout(tbdPnlConsultaFornecedores);
        tbdPnlConsultaFornecedores.setLayout(tbdPnlConsultaFornecedoresLayout);
        tbdPnlConsultaFornecedoresLayout.setHorizontalGroup(
            tbdPnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlConsultaFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbdPnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addGroup(tbdPnlConsultaFornecedoresLayout.createSequentialGroup()
                        .addComponent(lblDescricaoPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tbdPnlConsultaFornecedoresLayout.setVerticalGroup(
            tbdPnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbdPnlConsultaFornecedoresLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tbdPnlConsultaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoPesquisar)
                    .addComponent(txtNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdFornecedores.addTab("Consulta de fornecedorers", tbdPnlConsultaFornecedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tbdFornecedores)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(tbdFornecedores)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Fornecedor fornecedor = new Fornecedor();

        fornecedor.setNome(txtNome.getText());
        fornecedor.setCnpj(fmtCnpj.getText());
        fornecedor.setEmail(txtEmail.getText());
        fornecedor.setTelefone(fmtTelefone.getText());
        fornecedor.setCelular(fmtCelular.getText());
        fornecedor.setCep(fmtCep.getText());
        fornecedor.setEstado(cboUf.getSelectedItem().toString());
        fornecedor.setCidade(txtCidade.getText());
        fornecedor.setBairro(txtBairro.getText());
        fornecedor.setEndereco(txtEndereco.getText());
        try
        {
            fornecedor.setNumero(Integer.parseInt(txtNumero.getText()));
        }
        catch(Exception erro)
        {
            fornecedor.setNumero(0);
        }
        fornecedor.setComplemento(txtComplemento.getText());
        
        FornecedorDAO dao = new FornecedorDAO();

        dao.cadastrarFornecedor(fornecedor);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setId(Integer.parseInt(txtId.getText()));

        FornecedorDAO fornecedorDao = new FornecedorDAO();
        if(fornecedorDao.deletarFornecedor(fornecedor))
        {
            utilitarios.Utilitarios.LimpaTela(tbdPnlDadosBasicos);
            JOptionPane.showMessageDialog(null, "Fornecedor deletado com sucesso ;)");
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Fornecedor fornecedor = new Fornecedor();

        try
        {
            fornecedor.setId(Integer.parseInt(txtId.getText()));
        }
        catch(Exception erro)
        {
            fornecedor.setId(0);
        }
        fornecedor.setNome(txtNome.getText());
        fornecedor.setCnpj(fmtCnpj.getText());
        fornecedor.setEmail(txtEmail.getText());
        fornecedor.setTelefone(fmtTelefone.getText());
        fornecedor.setCelular(fmtCelular.getText());
        fornecedor.setCep(fmtCep.getText());
        fornecedor.setEstado(cboUf.getSelectedItem().toString());
        fornecedor.setCidade(txtCidade.getText());
        fornecedor.setBairro(txtBairro.getText());
        fornecedor.setEndereco(txtEndereco.getText());
        try
        {
            fornecedor.setNumero(Integer.parseInt(txtNumero.getText()));
        }
        catch(Exception erro)
        {
            fornecedor.setNumero(0);
        }
        fornecedor.setComplemento(txtComplemento.getText());
        
        FornecedorDAO dao = new FornecedorDAO();

        dao.alterarFornecedor(fornecedor);
        utilitarios.Utilitarios.LimpaTela(tbdPnlDadosBasicos);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNomePesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomePesquisarKeyReleased
        txtNomePesquisar.setText(txtNomePesquisar.getText().trim());
        listar(txtNomePesquisar.getText());
    }//GEN-LAST:event_txtNomePesquisarKeyReleased

    public void listar()
    {
        FornecedorDAO fornecedorDao = new FornecedorDAO();
        List<Fornecedor> fornecedores = fornecedorDao.obterFornecedores();
        
        DefaultTableModel tabelaDados = (DefaultTableModel) tblFornecedores.getModel();
        tabelaDados.setNumRows(0);
        
        for(Fornecedor fornecedor : fornecedores)
        {
            tabelaDados.addRow(
                new Object[]{
                    fornecedor.getId(),
                    fornecedor.getCnpj(),
                    fornecedor.getNome(),
                    fornecedor.getEmail(),
                    fornecedor.getTelefone(),
                    fornecedor.getCelular(),
                    fornecedor.getCep(),
                    fornecedor.getEstado(),
                    fornecedor.getCidade(),
                    fornecedor.getBairro(),
                    fornecedor.getEndereco(),
                    fornecedor.getNumero(),
                    fornecedor.getComplemento()
                }
            );
        }
    }
    
    public void listar(String nome)
    {
        FornecedorDAO fornecedorDao = new FornecedorDAO();
        List<Fornecedor> fornecedores = fornecedorDao.obterFornecedores(nome);
        
        DefaultTableModel tabelaDados = (DefaultTableModel) tblFornecedores.getModel();
        tabelaDados.setNumRows(0);
        
        for(Fornecedor fornecedor : fornecedores)
        {
            tabelaDados.addRow(
                new Object[]{
                    fornecedor.getId(),
                    fornecedor.getCnpj(),
                    fornecedor.getNome(),
                    fornecedor.getEmail(),
                    fornecedor.getTelefone(),
                    fornecedor.getCelular(),
                    fornecedor.getCep(),
                    fornecedor.getEstado(),
                    fornecedor.getCidade(),
                    fornecedor.getBairro(),
                    fornecedor.getEndereco(),
                    fornecedor.getNumero(),
                    fornecedor.getComplemento()
                }
            );
        }
    }
    
    private void tblFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMouseClicked
        tbdFornecedores.setSelectedIndex(0);
        int linha = tblFornecedores.getSelectedRow();

        txtId.setText(tblFornecedores.getValueAt(linha, 0).toString());
        fmtCnpj.setText(tblFornecedores.getValueAt(linha, 1).toString());
        txtNome.setText(tblFornecedores.getValueAt(linha, 2).toString());
        txtEmail.setText(tblFornecedores.getValueAt(linha, 3).toString());
        fmtTelefone.setText(tblFornecedores.getValueAt(linha, 4).toString());
        fmtCelular.setText(tblFornecedores.getValueAt(linha, 5).toString());
        fmtCep.setText(tblFornecedores.getValueAt(linha, 6).toString());
        cboUf.setSelectedItem(tblFornecedores.getValueAt(linha, 7).toString());
        txtCidade.setText(tblFornecedores.getValueAt(linha, 8).toString());
        txtBairro.setText(tblFornecedores.getValueAt(linha, 9).toString());
        txtEndereco.setText(tblFornecedores.getValueAt(linha, 10).toString());
        txtNumero.setText(tblFornecedores.getValueAt(linha, 11).toString());
        txtComplemento.setText(tblFornecedores.getValueAt(linha, 12).toString());
    }//GEN-LAST:event_tblFornecedoresMouseClicked

    private void tbdPnlConsultaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdPnlConsultaFornecedoresMouseClicked
        txtNomePesquisar.setText(txtNomePesquisar.getText().trim());
        listar();
    }//GEN-LAST:event_tbdPnlConsultaFornecedoresMouseClicked

    private void btnIdPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdPesquisarActionPerformed
        utilitarios.Utilitarios.LimpaTela(tbdPnlDadosBasicos);
    }//GEN-LAST:event_btnIdPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnIdPesquisar;
    private javax.swing.JComboBox<String> cboUf;
    private javax.swing.JFormattedTextField fmtCelular;
    private javax.swing.JFormattedTextField fmtCep;
    private javax.swing.JFormattedTextField fmtCnpj;
    private javax.swing.JFormattedTextField fmtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbINumero;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDescricaoPesquisar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUf;
    private javax.swing.JTabbedPane tbdFornecedores;
    private javax.swing.JPanel tbdPnlConsultaFornecedores;
    private javax.swing.JPanel tbdPnlDadosBasicos;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomePesquisar;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
